### ISSUE TITLE
Pick the name for the package - LogoFX.Templates

### ISSUE THREAD

**Issue by godrose** [LogoFX/cli-dotnet#16]
There are some options.
Namely, LogoFX.{Tools|Templates|Tooling|Templating}.{WPF|Client|Empty}

Please look at other examples and add here comments about the most appropriate name.

**Comment by dmitrybublik** [comment]
LogoFX.Templates.WPF

**Comment by godrose** [comment]
Please pay attention that the template pack should include also non-WPF specific templates:
https://github.com/LogoFX/cli-dotnet/milestone/2

**Comment by godrose** [comment]
@dmitrybublik @glyad

**Comment by godrose** [comment]
I think `LogoFX.Templates` would be more appropriate in light of https://github.com/LogoFX/cli-dotnet/milestone/2 contents
