### ISSUE TITLE
Devise the required functionality for the MVP

### ISSUE THREAD

**Issue by godrose** [LogoFX/cli-dotnet#5]
Related to #1

**Comment by glyad** [comment]
V.0.1.0
The version should include following:
1. The ability to generate a template from simplest LogoFX.WPF based solution:

1.1. Launcher
-  LogoFX.Templates.WPF.Launcher

1.2. Presentation
- LogoFX.Templates.WPF.Presentation
- LogoFX.Templates.WPF.Presentation.Contracts

1.3. Model
- LogoFX.Templates.WPF.Model
- LogoFX.Templates.WPF.Model.Contracts

1.4. Data
- LogoFX.Templates.WPF.Data.Contracts.Dto
- LogoFX.Templates.WPF.Data.Contracts.Providers
- LogoFX.Templates.WPF.Data.Fake.Containers.Contracts
- LogoFX.Templates.WPF.Data.Fake.Containers
- LogoFX.Templates.WPF.Data.Fake.ProviderBuilders
- LogoFX.Templates.WPF.Data.Fake.Providers
- LogoFX.Templates.WPF.Data.Real.Providers


2. The version's functionality and deliverables

2.1. The delivery should include the package, which is installable with `dotnet new -i c:\working\bin\Debug\LogoFX.WPF.Templates.1.0.0.nupkg` command. The package runnable with `dotnet new logofx-wpf [-n solution_name]`.

2.2. The solution created must include following use cases / items:
- Shell Window with Main View inside
- The sample item dto/model/item's view-model, and two contextual views (1. Is for display in collection and 2. Is for to display as a detailed representation of the item)
- The sample collection of items dto/model/item's view-model
- The simplest view/s to display Master/Details screen
- The editing cycle sample 


3. Using of default WPF styling only, but the layout must be good looking


4. Names:
- Use simple standard names for entities. like as Item, ItemsCollection, Value, Values... etc.

**Comment by godrose** [comment]
What’s the context for the Model/DTO? 
todo, warehouse, contacts, etc.?

**Comment by godrose** [comment]
This is the contents for 1.0.0 if I understand correctly?

**Comment by glyad** [comment]
> What’s the context for the Model/DTO?
> todo, warehouse, contacts, etc.?

ISampleItem { Id: GUID, DisplayName: string, Value: int } with following validation rules: DisplayName should be mandatory and between 5 and 12 symbols, the Value has default value 0 and must be in range of 0-999.

IEnumerable<ISampleItem> SampleItems as a master collection of sample items

**Comment by godrose** [comment]
What about the UI? Should we provide responsive UI in the MVP?

**Comment by glyad** [comment]
> This is the contents for 1.0.0 if I understand correctly?

This is the content for MVP. We discussed it with @dmitrybublik and agreed that the template must be delivered as a Nuget package anyway. It's based on definitions of the dotnet template pack, as it described here: [Tutorial: Create a template pack](https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-template-pack).

**Comment by glyad** [comment]
Really good example of the template pack: [RxWeb extensive packages](https://docs.rxweb.io/rx-web-core/quick-start/quick-start).

**Comment by godrose** [comment]
Please update the issue status and create child issues for further versions. 
If the issue itself is done close it accordingly.
